# Generated by Django 4.2.11 on 2024-05-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="imgae_name",
            new_name="image_name",
        ),
    ]
